args:
  latent_channels: 16
  mode: inference
  load: "/mnt/ceph/develop/jiawei/model_checkpoint/ckpts_2b_lora_tom_and_jerry_02/lora-disney-test" # This is for Full model without lora adapter
  # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter

  batch_size: 1
  input_type: txt
  input_file: /mnt/ceph/develop/jiawei/CogVideo/sat/configs/test.txt
  sampling_num_frames: 13  # Must be 13, 11 or 9
  sampling_fps: 8
  fp16: True # For CogVideoX-2B
#  bf16: True # For CogVideoX-5B
  output_dir: /mnt/ceph/develop/jiawei/CogVideo/sat/configs/outputs/
  force_inference: True